name: spatialhash
description: >
  An easy-to-use Spatial Hash implementation for Dart.
  Common use case is for collision detection in games or querying spatially-related data.
version: 1.0.1
repository: https://github.com/novemberisms/spatialhash
homepage: https://github.com/novemberisms/spatialhash

environment:
  sdk: ">=2.12.0 <3.0.0"

#dependencies:
#  path: ^1.4.1

dev_dependencies:
  test: ^1.0.0
